Parameters:
  DBInstanceClass:
    Default: db.t3.medium
    Description: DB instance class
    Type: String
  DBUsername:
    NoEcho: 'true'
    Description: Username for rds-postgres database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password rds-postgres database access
    Type: String
    MinLength: '6'
    MaxLength: '41'
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  RDSCluster:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: colorToRGBPostgres
      DBName: colorToRGBPostgres
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: '14.1'